### ISSUE TITLE
error of ol not found while usage in react

### ISSUE THREAD

**Issue by mumairr** [OpenCageData/geosearch#175]
While using it in a react based OL application, it gives following error:

ol is not defined
    at ./node_modules/@opencage/ol-opencage-geosearch/ol-opencage-geosearch.js

any guides pls?

**Comment by tsamaya** [comment]
Hi,
do you have included the OpenLayer dependency in your project, it is a peer dependency for the OL widget: https://github.com/OpenCageData/geosearch/blob/master/packages/ol-opencage-geosearch/package.json#L40

**Comment by mumairr** [comment]
Yes I have. If i remove @opencage/ol-opencage-geosearch from the code, app runs perfetly fine, as soon as I add the control, app gives the above error.
I am using latest react, ol, ol-ext already

**Comment by tsamaya** [comment]
Interesting, could you you please share an example reproducing the issue in a GitHub repository or anything like : [codesandbox](https://codesandbox.io/) or [stackblitz](https://stackblitz.com/) . That would help me to investigate the issue 

⚠️ do not share your opencage geosearch key.

**Comment by mumairr** [comment]
Sure.
I have created a public repo with minimalist options required to reproduce the issue:

https://github.com/mumairr/OpenCage-GeoSearch-Example

Let me know if you face issues accessing it, Thanks

**Comment by tsamaya** [comment]
Thank you. I can see the problem now. 
We ship the plugin as an old fashion JS module, ie: not ESM. Hence the react script bundler assumes it is an all-in-one module. Configuring webpack on your project might be complicated. I will find you a workaround and add to our roadmap exposing the modules as ESM.

**Comment by mumairr** [comment]
Thank you for the update.
I look forward to it.

**Comment by tsamaya** [comment]
I created this PR https://github.com/mumairr/OpenCage-GeoSearch-Example/pull/1 on your repo.
This will allow you to execute the plugin and keep building your app.
I created this issue #182 to expose the core package, the plugin OL and Leaflet as ESM modules.

Please let me know if the PR can help and what your deadline is on your React application.

**Comment by tsamaya** [comment]
Closing this issue:
- workaround: provided
- #182: created
